name: eco_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  clippy_flutter: ^1.1.1
  auto_route: ^2.3.2
  salomon_bottom_bar: ^3.1.0
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.6
  image: ^3.2.2
  collection: ^1.16.0
  tflite_flutter: ^0.9.0
  custom_info_window: ^1.0.1
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  auto_route_generator: ^2.3.2
  build_runner: ^2.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/photo_1.jpeg
    - assets/photo_2.jpeg
    - assets/photo_3.jpeg
    - assets/photo_4.jpeg
    - assets/glass_photo.jpeg
    - assets/paper_photo.jpeg
    - assets/plastic_photo.jpeg
    - assets/metal_photo.jpeg
    - assets/medical_photo.jpeg
    - assets/elec_photo.jpeg
    - assets/tetra_photo.jpg
    - assets/map_style.json
    - assets/labels.txt
    - assets/model_unquant.tflite
flutter_icons:
  image_path_ios: 'assets/icon.jpeg'
  image_path_android: 'assets/icon.jpeg'
  android: true
  ios: true